---
apiVersion: v1
kind: Service
metadata:
  name: file-server-service
  namespace: misc
spec:
  type: NodePort
  selector:
    app: file-server
  ports:
    - port: 3010
      name: http
      targetPort: 8080
      nodePort: 30100
    - port: 4005
      name: swank
      targetPort: 4005
      nodePort: 30102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: file-server
          image: macnod/file-server:{{VERSION}}
          imagePullPolicy: Never
          command: ["ros"]
          args:
            - "run"
            - "--"
            - "--eval"
            - "(require :file-server)"
            - "--eval"
            - "(in-package :file-server)"
            - "--eval"
            - "(run)"
          ports:
            - containerPort: 8080
            - containerPort: 4005
          env:
            - name: FILE_MANAGER_VERSION
              value: {{VERSION}}
            # Database connection
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "fileserver"
            - name: DB_USER
              value: "fileserver"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-secrets
                  key: postgres-password
            # Admin user, with access to all resources
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-secrets
                  key: admin-user-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: file-server-secrets
                  key: jwt-secret
            - name: LOG_SEVERITY
              value: debug
            - name: LOG_SUPPRESS_HEALTH
              value: "true"
            - name: WEB_DIRECTORY
              value: "/app/web"
          volumeMounts:
            - mountPath: /app
              name: file-server-volume
      volumes:
        - name: file-server-volume
          hostPath:
            path: /home/macnod/common-lisp/file-server
            type: Directory
