# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: file-server-secrets
  namespace: misc
type: Opaque
data:
  root-user-password: BASE64-ENCODED-PASSWORD
  postgres-password: BASE64-ENCODED-PASSWORD
  jwt-secret: BASE64-ENCODED-32-CHAR-SECRET
