environment: dev

namespace: misc

fileServer:
  port: 3021
  nodePort: 30211
  memory: 4Gi
  requests:
    cpu: 250m
  limits:
    cpu: 1000m
  storageSize: 1Gi
  image:
    pullPolicy: IfNotPresent
    # This will be set by the build script
    tag: "0.0.0"

swankServer:
  port: 4106
  nodePort: 30221

postgres:
  image: postgres:16.10
  port: 5441
  nodePort: 30201
  storageSize: 100Mi

utility:
  image: busybox:1.36
