apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-server-{{ .Values.environment }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "file-server.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.fileServer.storageSize | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/file-server/{{ .Values.environment }}
    type: DirectoryOrCreate
