apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-{{ .Values.environment }}-deployment
  labels:
    {{- include "file-server.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "file-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "file-server.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: init-storage
          image: {{ .Values.postgres.image }}
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for PostgreSQL..."
              TIMEOUT=20
              START=$(date +%s)
              until pg_isready -h $DB_HOST -p $DB_PORT -U fileserver -d fileserver; do
                NOW=$(date +%s)
                ELAPSED=$((NOW - START))
                if [ $ELAPSED -ge $TIMEOUT ]; then
                  echo "PostgreSQL timeout after ${TIMEOUT} seconds"
                  exit 1
                fi
                echo "Postgres not ready - waiting..."
                sleep 2
              done
              echo "PostgreSQL ready after $ELAPSED seconds"
          env:
            - name: DB_HOST
              value: postgres-{{ .Values.environment }}-service
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: postgres-password
          volumeMounts:
            - name: file-server-volume
              mountPath: /app/shared-files
      containers:
        - name: file-server
          image: macnod/file-server:{{ .Values.fileServer.image.tag }}
          imagePullPolicy: {{ .Values.fileServer.image.pullPolicy }}
          command: ["ros"]
          args:
            - "run"
            - "--"
            - "--eval"
            - "(require :file-server)"
            - "--eval"
            - "(in-package :file-server)"
            - "--eval"
            - "(run)"
          ports:
            - containerPort: 8080
            - containerPort: 4005
          resources:
            requests:
              memory: {{ .Values.fileServer.memory }}
              cpu: {{ .Values.fileServer.requests.cpu }}
            limits:
              memory: {{ .Values.fileServer.memory }}
              cpu: {{ .Values.fileServer.limits.cpu }}
          env:
            - name: FILE_MANAGER_VERSION
              value: {{ .Values.fileServer.image.tag | quote }}
            - name: FILE_MANAGER_ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: DB_HOST
              value: postgres-{{ .Values.environment }}-service
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: DB_NAME
              value: "fileserver"
            - name: DB_USER
              value: "fileserver"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: postgres-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: admin-user-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: jwt-secret
            - name: LOG_SEVERITY
              value: debug
            - name: LOG_SUPPRESS_HEALTH
              value: "true"
            - name: WEB_DIRECTORY
              value: "/app/web"
            - name: FS_DOCUMENT_ROOT
              value: "/app/shared-files/"
            - name: FS_TEMP_DIRECTORY
              values: "/app/temp-files/"
          volumeMounts:
            - mountPath: /app
              name: file-server-volume
      volumes:
        - name: file-server-volume
          persistentVolumeClaim:
            claimName: file-server-{{ .Values.environment }}-pvc
