#!/bin/bash

source scripts/version.sh

SCRIPT_NAME=$(basename $0)
VERSION_FILE="version.txt"

save_version() {
    echo "$VERSION" > "$VERSION_FILE"
}

function usage {
    echo "Usage: $SCRIPT_NAME [options]"
    echo 
    echo "This script generates file-server.yaml and then builds a file-server container"
    echo "macnod/file-server:{version}. The --version option is required."
    echo
    echo "Options:"
    echo "  --env          The environment: prod or dev"
    echo "  --version      The version of the image to build, in format X.XX.XX"
    echo "  --no-cache     Don't use the cache at all when building the image."
    echo "  --render-only  Don't build. Just create file-server.yaml."
    echo "  --help         Display this help screen."
    echo
    echo "Notes:"
    echo "  - If --no-cache is omitted, then 3rd party packages are cached, but local"
    echo "    packages that are in flux are not cached."
}

load_version
DEPLOY_TO=""
NO_CACHE=false
RENDER_ONLY=false
SOURCE_CONF=""
TARGET_CONF=""
PORT=0
TARGET_PORT=0
NODE_PORT=0
DB_PORT=0


# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --env)
            shift
            DEPLOY_TO="$1"
            ;;
        --version)
            shift
            VERSION="$1"
            check_version
            echo "Overriding next version $VERSION with $1"
            VERSION="$1"
            ;;
        --no-cache)
            NO_CACHE=true
            ;;
        --render-only)
            RENDER_ONLY=true
            ;;
        --help)
            HELP=true
            usage
            exit 0
            ;;
        *)
            usage
            echo "Unknown option $1"
            ;;
    esac
    shift
done

# Set some variables according to the environment (dev or prod)
case "$DEPLOY_TO" in
    dev)
        DOCKERFILE="dev/Dockerfile"
        IMAGE="file-server-dev"
        SOURCE_CONF="dev/kube/file-server-template.yaml"
        TARGET_CONF="dev/kube/file-server.yaml"
        SOURCE_PG_CONF="dev/kube/postgres-template.yaml"
        TARGET_PG_CONF="dev/kub/postgres.yaml"
        PORT=3110
        NODE_PORT=30210
        DB_PORT=5440
        ;;
    prod)
        DOCKERFILE="prod/Dockerfile"
        IMAGE="file-server"
        SOURCE_CONF="prod/kube/file-server-template.yaml"
        TARGET_CONF="prod/kube/file-server.yaml"
        SOURCE_PG_CONF="prod/kube/postgres-template.yaml"
        TARGET_PG_CONF="prod/kub/postgres.yaml"
        PORT=3111
        NODE_PORT=30211
        DB_PORT=5441
        DB_NODE_PORT=
        SWANK_PORT=3211
        SWANK_NODE_PORT=30211
        ;;
    *)
        usage
        echo "Bad value for --env: $DEPLOY_TO"
        ;;
esac

# Create file-server.yaml from file-server-template.yaml
{
    echo "# NOTE: This file is autogenerated from $SOURCE_CONF"
    echo
    sed -e "s/\$VERSION/$VERSION/g" \
        -e "s/\$IMAGE/$IMAGE/g" \
        -e "s/\$ENVIRONMENT/$DEPLOY_TO/g" \
        -e "s/\$PORT/$PORT/g" \
        -e "s/\$NODE_PORT/$NODE_PORT/g"
        $SOURCE_CONF
} > $TARGET_CONF

# Create postgres.yaml from postgres-template.yaml
{
    echo "# NOTE: This file is autogenerated from $SOURCE_CONF"
    echo
    sed -e "s/\$VERSION/$VERSION/g" \
        -e "s/\$ENVIRONMENT/$DEPLOY_TO/g" \
        -e "s/\$NODE_PORT/$NODE_PORT/g"
        -e "s/\$DB_NODE_PORT/$DB_NODE_PORT/g"
        $SOURCE_CONF
} > $TARGET_CONF

# Select the caching approach
if [ "$NO_CACHE" = true ]; then
    CACHE_OPTION="--no-cache"
else
    CACHE_OPTION="--build-arg CACHEBUST=$(date +%s)"
fi

docker build -f "$DOCKERFILE" \
       $CACHE_OPTION \
       -t "macnod/$IMAGE:$VERSION" \
       -t "macnod/$IMAGE:latest" .
