#!/bin/bash

SCRIPT_NAME=$(basename $0)

function usage {
    echo "Usage: $SCRIPT_NAME [options]"
    echo 
    echo "This script generates file-server.yaml and then builds a file-server container"
    echo "macnod/file-server:{version}. The --version option is required."
    echo
    echo "Options:"
    echo "  --env       The environment: prod or dev"
    echo "  --version   The version of the image to build, like 0.12."
    echo "  --no-cache  Don't use the cache at all when building the image."
    echo "  --help      Display this help screen."
    echo
    echo "Notes:"
    echo "  - If --no-cache is omitted, then 3rd party packages are cached, but local"
    echo "    packages that are in flux are not cached."
    if [ "$HELP" = true ]; then
        exit 0
    else
        exit 1
    fi
}

VERSION=""
NO_CACHE=false
HELP=false

# Read the environment from the file './environment'. The file should have a
# single line with the word prod or dev.
read -r DEPENV < environment

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --version)
            shift
            VERSION="$1"
            ;;
        --no-cache)
            NO_CACHE=true
            ;;
        --help)
            HELP=true
            usage
            ;;
        *)
            usage
            ;;
    esac
    shift
done

# Check if DEPENV is empty
if [ -z "$DEPENV" ]; then
    echo "Error: Check the file ./environment. It should have 'dev' or 'prod'"
    exit 1
fi

# Check if VERSION is empty
if [ -z "$VERSION" ]; then
    echo "Error: Version is required. Use --version <major>.<minor>"
    exit 1
fi

# Set some variables according to the environment (dev or prod)
case "$DEPENV" in
    dev)
        DOCKERFILE="Dockerfile-dev"
        IMAGE="file-server-dev"
        ;;
    prod)
        DOCKERFILE="Dockerfile"
        IMAGE="file-server"
        ;;
    *)
        echo "Bad value for --env: $DEPENV"
        usage
        ;;
esac

# Create file-server.yaml from file-server-template.yaml
{
    echo "# NOTE: This file is autogenerated from kube/file-server-template.yaml"
    echo
    sed -e "s/\$VERSION/$VERSION/g" \
        -e "s/\$IMAGE/$IMAGE/g" \
        -e "s/\$ENVIRONMENT/$DEPENV/g" \
        kube/file-server-template.yaml
} > kube/file-server.yaml

# Select the caching approach
if [ "$NO_CACHE" = true ]; then
    CACHE_OPTION="--no-cache"
else
    CACHE_OPTION="--build-arg CACHEBUST=$(date +%s)"
fi

docker build -f "$DOCKERFILE" \
       $CACHE_OPTION \
       -t "macnod/$IMAGE:$VERSION" \
       -t "macnod/$IMAGE:latest" .
