# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: file-server-prod-secrets
  namespace: misc
type: Opaque
data:
  admin-user-password: base64-encoded-admin-password
  postgres-password: base64-encoded-pg-password
  jwt-secret: base64-encoded-jwt-secret
