---
apiVersion: v1
kind: Service
metadata:
  name: file-server-$ENVIRONMENT-service
  namespace: misc
spec:
  type: NodePort
  selector:
    app: file-server-$ENVIRONMENT
  ports:
    - port: $PORT
      name: http
      targetPort: 8080
      nodePort: $NODE_PORT
    - port: 4105
      name: swank
      targetPort: 4005
      nodePort: 30211
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-$ENVIRONMENT-deployment
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server-$ENVIRONMENT
  template:
    metadata:
      labels:
        app: file-server-$ENVIRONMENT
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: file-server
          image: macnod/$IMAGE:$VERSION
          imagePullPolicy: Never
          command: ["ros"]
          args:
            - "run"
            - "--"
            - "--eval"
            - "(require :file-server)"
            - "--eval"
            - "(in-package :file-server)"
            - "--eval"
            - "(run)"
          ports:
            - containerPort: 8080
            - containerPort: 4005
          resources:
            requests:
              memory: "4Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          env:
            - name: FILE_MANAGER_VERSION
              value: $VERSION
            - name: FILE_MANAGER_ENVIRONMENT
              value: $ENVIRONMENT
            # Database connection
            - name: DB_HOST
              value: "postgres-$ENVIRONMENT-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "fileserver"
            - name: DB_USER
              value: "fileserver"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-$ENVIRONMENT-secrets
                  key: postgres-password
            # Admin user, with access to all resources
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-$ENVIRONMENT-secrets
                  key: admin-user-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: file-server-$ENVIRONMENT-secrets
                  key: jwt-secret
            - name: LOG_SEVERITY
              value: debug
            - name: LOG_SUPPRESS_HEALTH
              value: "true"
            - name: WEB_DIRECTORY
              value: "/app/web"
          volumeMounts:
            - mountPath: /app
              name: file-server-$ENVIRONMENT-volume
      volumes:
        - name: file-server-$ENVIRONMENT-volume
          hostPath:
            path: /home/macnod/common-lisp/file-server/$ENVIRONMENT
            type: Directory
